### ISSUE TITLE
Callback Error Updating store-trips.data - TypeError: 'float' object is not subscriptable

### ISSUE THREAD

**Issue by TeachMeTW** [e-mission/op-admin-dashboard#120]
### Description

We are encountering a `TypeError` while updating `store-trips.data`. The error traceback indicates that there is an issue with the function applied to the `ble_sensed_summary` column in the DataFrame. The error occurs because a `float` object is being treated as if it were a dictionary.

### Traceback
```
Callback error updating store-trips.data Traceback (most recent call last): File "/usr/src/app/app_sidebar_collapsible.py", line 318, in update_store_trips df, user_input_cols = query_confirmed_trips(start_date, end_date, timezone) File "/usr/src/app/utils/db_utils.py", line 101, in query_confirmed_trips df["data.primary_ble_sensed_mode"] = df.ble_sensed_summary.apply(get_max_mode_from_summary) File "/root/miniconda-23.5.2/envs/emission/lib/python3.9/site-packages/pandas/core/series.py", line 4771, in apply return SeriesApply(self, func, convert_dtype, args, kwargs).apply() File "/root/miniconda-23.5.2/envs/emission/lib/python3.9/site-packages/pandas/core/apply.py", line 1123, in apply return self.apply_standard() File "/root/miniconda-23.5.2/envs/emission/lib/python3.9/site-packages/pandas/core/apply.py", line 1174, in apply_standard mapped = lib.map_infer( File "pandas/_libs/lib.pyx", line 2924, in pandas._libs.lib.map_infer File "/usr/src/app/utils/db_utils.py", line 97, in <lambda> get_max_mode_from_summary = lambda md: max(md["distance"], key=md["distance"].get) if len(md["distance"]) > 0 else "INVALID" TypeError: 'float' object is not subscriptable
```

### Issue

The `TypeError` occurs because the lambda function `get_max_mode_from_summary` expects `md` to be a dictionary with a `"distance"` key that maps to another dictionary. However, it appears that some entries in `ble_sensed_summary` are `float` values, which are not subscriptable and thus lead to this error.

### Steps to Reproduce

1. Call the `update_store_trips` function with appropriate parameters.
2. Observe the error traceback indicating the `TypeError`.

### Expected Behavior

The `ble_sensed_summary` column should be processed correctly, and the `get_max_mode_from_summary` function should handle various data types properly without raising an error.

### Suggested Fix

Update the `get_max_mode_from_summary` lambda function to handle cases where `md` is not a dictionary. For example:

```python
get_max_mode_from_summary = lambda md: (
    "INVALID" if not isinstance(md, dict) or "distance" not in md or not isinstance(md["distance"], dict) else
    (max(md["distance"], key=md["distance"].get) if len(md["distance"]) > 0 else "INVALID")
)

Consider adding data validation or cleaning steps before applying the lambda function.

**Comment by JGreenlee** [comment]
Can you show or point me to one of these malformed `ble_sensed_summary` entries?

The summaries should have this shape
<img width="514" alt="image" src="https://github.com/user-attachments/assets/d2fafc62-0815-461b-a7bb-b4e906ec8a19">


If that's not the case, there is an issue with the data

**Comment by shankari** [comment]
I wonder if this and https://github.com/e-mission/em-public-dashboard/issues/142 are related

**Comment by TeachMeTW** [comment]
Utilized this function below to check for invalid data in ble, primary_predicted, and primary_sensed; only ble data is flagged as 'nan'

```
        if 'ble_sensed_summary' in df.columns:
            df["data.primary_ble_sensed_mode"] = df.ble_sensed_summary.apply(
                lambda md: (
                    (
                        max(md["distance"], key=md["distance"].get) 
                        if len(md["distance"]) > 0
                        else "INVALID"
                    )
                    if isinstance(md, dict) and "distance" in md
                    else (
                        logging.debug(f"Skipping entry due to invalid format or missing 'distance' in BLE Sensed Mode: {md}"),
                        "ERROR"
                    )[1]
                )
            )
        else:
            logging.debug("No BLE support found, not fleet version, ignoring...")```
