### ISSUE TITLE
Adding a User Details page

### ISSUE THREAD

**Issue by AlirezaRa94** [e-mission/op-admin-dashboard#59]
@shankari 
I've introduced a new dashboard page that filters data for individual users. This page displays daily trips and places, along with relevant statistics. It's designed to track users' progress in filling out time-use data across different days. If you believe this feature could benefit other programs or studies, I'm happy to provide further information and make a pull request.
I'm working on it here:
https://github.com/AlirezaRa94/op-admin-dashboard/tree/feat/user_page

**Comment by shankari** [comment]
@AlirezaRa94  in general, you might want to submit all the new functionality that you build, just making sure that it is controlled by the dynamic config. We might remove functionality later if we find that it is unused, but the admin dashboard is very limited right now so it is likely that any new functionality that you add is likely to be useful to other programs as well. If we find that a particular piece of functionality is unused, we can remove it after a year or so.
