### ISSUE TITLE
Trajectory table is not getting filtered by date range.

### ISSUE THREAD

**Issue by achasmita** [e-mission/op-admin-dashboard#72]
I tried same method used in trip table and passed start_date and end_date as an  input but the filter did not work.
I also tried creating separate callback for trajectory table in data page that also did not work.
It is reading the data but there is no change in table as expected.
![Screen Shot 2023-09-29 at 3 21 50 PM](https://github.com/e-mission/op-admin-dashboard/assets/79387860/4c7ee8c8-d134-4ab7-be10-a488a8f22edc)

**Comment by shankari** [comment]
@achasmita lets continue discussing this in the issue. What do you mean by "the filter did not work" other than the amount of data loaded.

What did you do to debug the filter and to see if the values were passed through correctly?

**Comment by achasmita** [comment]
ok I was doing wrong while passing date , I reverted and tried it again and it works now both way.

**Comment by shankari** [comment]
Can you also record in here how you were passing the date before and what the correct way to pass it is? Again, will help with context for the future, including for you!

**Comment by achasmita** [comment]
``` df = query_trajectories(start_date_obj,end_date_obj)``` I was passing None everytime here while querying data instead of date range selected by user.

**Comment by shankari** [comment]
Fixed by https://github.com/e-mission/op-admin-dashboard/pull/71
